### PR TITLE
Fix/web new chat room improvements

### LINKED ISSUE #491: Web - new chat room - improvements
UX/UI improvements required for “Create new chat” interface

Screenshot 2023-08-10 at 10 05 34

Maybe look into how it’s done in other messengers

I think title here should be renamed to

“Create a new room”

+ add description for example:
Your new chat room will only be visible to you initially but you can invite other users via QR code or short link. 

+ improve the UI a bit, for example next to Chat Name it would be good to display a red * to show this field is mandatory

also “profile” icon is a bit confusing, needs to be replaced with another image which better symbolizes that this is a chat room thumbnail and also should have some guidance regarding the recommended image sizes here I guess

buttons (Submit) I would rather align left (or right) rather than center

### PR DESCRIPTION
**Pull request by aasimtaif**
# Pull Request
fixes #491 

## Description
Improved the UX/UI for "create new chat " interface

## Changes Made
changed "create new chat "  to "create new room "
added a red asterisk * in the Chat Name field to show that it is mandatory
Changed the profile image with an image icon and a + sign which will help users identify it as an image upload field
Change the interface to a responsive UI
 

## Screenshots (if applicable)
If your changes include visual updates, provide screenshots or GIFs to showcase the before and after states.
Screenshot from 2023-09-07 23-16-26

## Checklist
- [x] I have tested these changes locally.
- [x] I have reviewed the code changes and ensured adherence to the project's coding standards.
- [x] I have updated the project documentation, if necessary.
- [x] I have checked for any potential conflicts with other branches.

Please review and merge this pull request once it meets the necessary criteria. Thank you!

### CODE REVIEW

**Comment by aasimtaif** [comment]
If you want some improvements please let me know

**Comment by transkarpation** [comment]
> 

I wrote to you that, in my opinion, there are some issues with your PR. It's up to you to decide if you want to change your code to meet the requirements. In addition to those three points, a good improvement would be if you added the ability to crop images for the chat.

**Comment by aasimtaif** [comment]
> > 
> 
> I wrote to you that, in my opinion, there are some issues with your PR. It's up to you to decide if you want to change your code to meet the requirements. In addition to those three points, a good improvement would be if you added the ability to crop images for the chat.

I am happy to improve the code to meet the requirements.
Working on the image crop option

**Comment by aasimtaif** [comment]
I am trying to post the cropped image to backend but  It is giving me error
Screenshot from 2023-09-15 16-14-50

` const inputRef = useRef<HTMLInputElement>(null);
  const cropperRef = useRef<CropperRef>(null);

  const [image, setImage] = useState(
    '',
  );

  const onCrop = () => {
    const cropper = cropperRef.current;
    if (cropper) {
      const canvas = cropper.getCanvas()

      if (canvas) {
        let file = new File([canvas.toDataURL()], "newAvatar.png", { type: "image/png" })
        console.log(file)
        onFileChange(file)

      }
    }
  };
  const onLoadImage = (event: ChangeEvent<HTMLInputElement>) => {
    handleOpen()
    if (inputRef.current) {
      inputRef.current.click();
    }
    console.log(event.target)
    const file = event.target.files && event.target.files[0];
    if (file) {
      setImage(URL.createObjectURL(file));
    }
  };
  
  const onFileChange = async (e: any) => {
    setLoading(true);
    console.log(e)
    try {
      const fd = new FormData();
      fd.append("files", e);
      const fileUploadResp = await httpWithAuth().post("/files", fd);
      console.log(fd, fileUploadResp)
      formik.setValues((prev) => ({
        ...prev,
        chatImage: fileUploadResp.data.results[0].location,
      }));
      console.log(fileUploadResp.data.results[0].location)
    } catch (error) {
      console.log(error);
    }
    setLoading(false);
    handleClose()
  };`
I am using react-advanced-cropper Liberary

**Comment by aasimtaif** [comment]
When I try to post  cropped image it is giving me error as 
Screenshot from 2023-09-15 16-14-50

` 
const inputRef = useRef<HTMLInputElement>(null);
  const cropperRef = useRef<CropperRef>(null);

  const [image, setImage] = useState(
    '',
  );

  const onCrop = () => {
    const cropper = cropperRef.current;
    if (cropper) {
      const canvas = cropper.getCanvas()

      if (canvas) {
        let file = new File([canvas.toDataURL()], "newAvatar.png", { type: "image/png" })
        console.log(file)
        onFileChange(file)

      }
    }
  };
`

**Comment by aasimtaif** [comment]
`const onCrop = () => {
    const cropper = cropperRef.current;
    if (cropper) {
      const canvas = cropper.getCanvas()

      if (canvas) {
        let file = new File([canvas.toDataURL()], "newAvatar.png", { type: "image/png" })
        console.log(file)
        onFileChange(file)

      }
    }
  }`

**Comment by aasimtaif** [comment]
```
const onCrop = () => {
    const cropper = cropperRef.current;
    if (cropper) {
      const canvas = cropper.getCanvas()

      if (canvas) {
        let file = new File([canvas.toDataURL()], "newAvatar.png", { type: "image/png" })
        console.log(file)
        onFileChange(file)

      }
    }
  }
```

**Comment by dzinzyura** [comment]
Hi @aasimtaif !

Thanks for sharing this issue with us. Our team is currently addressing it and will reach out to you shortly with our insights and recommendations.

Best regards,
Vladyslav
Ethora team

**Comment by transkarpation** [comment]
> when i try to post the cropped image it is giving me error, I am using react-advance-cropper Screenshot from 2023-09-15 16-14-50
> 
> ```
>   const inputRef = useRef<HTMLInputElement>(null);
>   const cropperRef = useRef<CropperRef>(null);
> 
>   const [image, setImage] = useState(
>     ' ',
>   );
> const onCrop = () => {
>     const cropper = cropperRef.current;
>     if (cropper) {
>       const canvas = cropper.getCanvas()
> 
>       if (canvas) {
>         let file = new File([canvas.toDataURL()], "newAvatar.png", { type: "image/png" })
>         console.log(file)
>         onFileChange(file)
> 
>       }
>     }
>   }
>  const onLoadImage = (event: ChangeEvent<HTMLInputElement>) => {
>     handleOpen()
>     if (inputRef.current) {
>       inputRef.current.click();
>     }
>     console.log(event.target)
>     const file = event.target.files && event.target.files[0];
>     if (file) {
>       setImage(URL.createObjectURL(file));
>     }
>   };
> 
>   const onFileChange = async (e: any) => {
>     setLoading(true);
>     console.log(e)
>     try {
>       const fd = new FormData();
>       fd.append("files", e);
>       const fileUploadResp = await httpWithAuth().post("/files", fd);
>       console.log(fd, fileUploadResp)
>       formik.setValues((prev) => ({
>         ...prev,
>         chatImage: fileUploadResp.data.results[0].location,
>       }));
>       console.log(fileUploadResp.data.results[0].location)
>     } catch (error) {
>       console.log(error);
>     }
>     setLoading(false);
>     handleClose()
>   };
> ```
> 
> ```
>  <Modal
>         open={open}
>         onClose={handleClose}
>         aria-labelledby="modal-modal-title"
>         aria-describedby="modal-modal-description"
>       >
>         <Box sx={style}>
>           <Cropper
>             ref={cropperRef}
>             src={image}
>             className="example__cropper"
>             backgroundClassName="example__cropper-background"
>           />
>           {image && (<>
>             <button className="example__button" onClick={onCrop}>
>               Set Image
>             </button>
>           </>)}
>         </Box>
>       </Modal>
> 
> 
>  <input
>             accept="image/*"
>             style={{ display: "none" }}
>             id="raised-button-file"
>             type="file"
>             ref={inputRef}
>             onChange={onLoadImage}
>           />
> ```

push your code to github first

**Comment by aasimtaif** [comment]
> > when i try to post the cropped image it is giving me error, I am using react-advance-cropper Screenshot from 2023-09-15 16-14-50
> > ```
> >   const inputRef = useRef<HTMLInputElement>(null);
> >   const cropperRef = useRef<CropperRef>(null);
> > 
> >   const [image, setImage] = useState(
> >     ' ',
> >   );
> > const onCrop = () => {
> >     const cropper = cropperRef.current;
> >     if (cropper) {
> >       const canvas = cropper.getCanvas()
> > 
> >       if (canvas) {
> >         let file = new File([canvas.toDataURL()], "newAvatar.png", { type: "image/png" })
> >         console.log(file)
> >         onFileChange(file)
> > 
> >       }
> >     }
> >   }
> >  const onLoadImage = (event: ChangeEvent<HTMLInputElement>) => {
> >     handleOpen()
> >     if (inputRef.current) {
> >       inputRef.current.click();
> >     }
> >     console.log(event.target)
> >     const file = event.target.files && event.target.files[0];
> >     if (file) {
> >       setImage(URL.createObjectURL(file));
> >     }
> >   };
> > 
> >   const onFileChange = async (e: any) => {
> >     setLoading(true);
> >     console.log(e)
> >     try {
> >       const fd = new FormData();
> >       fd.append("files", e);
> >       const fileUploadResp = await httpWithAuth().post("/files", fd);
> >       console.log(fd, fileUploadResp)
> >       formik.setValues((prev) => ({
> >         ...prev,
> >         chatImage: fileUploadResp.data.results[0].location,
> >       }));
> >       console.log(fileUploadResp.data.results[0].location)
> >     } catch (error) {
> >       console.log(error);
> >     }
> >     setLoading(false);
> >     handleClose()
> >   };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> >  <Modal
> >         open={open}
> >         onClose={handleClose}
> >         aria-labelledby="modal-modal-title"
> >         aria-describedby="modal-modal-description"
> >       >
> >         <Box sx={style}>
> >           <Cropper
> >             ref={cropperRef}
> >             src={image}
> >             className="example__cropper"
> >             backgroundClassName="example__cropper-background"
> >           />
> >           {image && (<>
> >             <button className="example__button" onClick={onCrop}>
> >               Set Image
> >             </button>
> >           </>)}
> >         </Box>
> >       </Modal>
> > 
> > 
> >  <input
> >             accept="image/*"
> >             style={{ display: "none" }}
> >             id="raised-button-file"
> >             type="file"
> >             ref={inputRef}
> >             onChange={onLoadImage}
> >           />
> > ```
> 
> push your code to github first

Ok

**Comment by aasimtaif** [comment]
> > when i try to post the cropped image it is giving me error, I am using react-advance-cropper Screenshot from 2023-09-15 16-14-50
> > ```
> >   const inputRef = useRef<HTMLInputElement>(null);
> >   const cropperRef = useRef<CropperRef>(null);
> > 
> >   const [image, setImage] = useState(
> >     ' ',
> >   );
> > const onCrop = () => {
> >     const cropper = cropperRef.current;
> >     if (cropper) {
> >       const canvas = cropper.getCanvas()
> > 
> >       if (canvas) {
> >         let file = new File([canvas.toDataURL()], "newAvatar.png", { type: "image/png" })
> >         console.log(file)
> >         onFileChange(file)
> > 
> >       }
> >     }
> >   }
> >  const onLoadImage = (event: ChangeEvent<HTMLInputElement>) => {
> >     handleOpen()
> >     if (inputRef.current) {
> >       inputRef.current.click();
> >     }
> >     console.log(event.target)
> >     const file = event.target.files && event.target.files[0];
> >     if (file) {
> >       setImage(URL.createObjectURL(file));
> >     }
> >   };
> > 
> >   const onFileChange = async (e: any) => {
> >     setLoading(true);
> >     console.log(e)
> >     try {
> >       const fd = new FormData();
> >       fd.append("files", e);
> >       const fileUploadResp = await httpWithAuth().post("/files", fd);
> >       console.log(fd, fileUploadResp)
> >       formik.setValues((prev) => ({
> >         ...prev,
> >         chatImage: fileUploadResp.data.results[0].location,
> >       }));
> >       console.log(fileUploadResp.data.results[0].location)
> >     } catch (error) {
> >       console.log(error);
> >     }
> >     setLoading(false);
> >     handleClose()
> >   };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> >  <Modal
> >         open={open}
> >         onClose={handleClose}
> >         aria-labelledby="modal-modal-title"
> >         aria-describedby="modal-modal-description"
> >       >
> >         <Box sx={style}>
> >           <Cropper
> >             ref={cropperRef}
> >             src={image}
> >             className="example__cropper"
> >             backgroundClassName="example__cropper-background"
> >           />
> >           {image && (<>
> >             <button className="example__button" onClick={onCrop}>
> >               Set Image
> >             </button>
> >           </>)}
> >         </Box>
> >       </Modal>
> > 
> > 
> >  <input
> >             accept="image/*"
> >             style={{ display: "none" }}
> >             id="raised-button-file"
> >             type="file"
> >             ref={inputRef}
> >             onChange={onLoadImage}
> >           />
> > ```
> 
> push your code to github first

Done

**Comment by aasimtaif** [comment]
can you help me resolve this issue

**Comment by transkarpation** [comment]
> can you help me resolve this issue?

you did not fix issues with your previos commit (.env-example is steel deleted)

**Comment by phwizard** [comment]
@transkarpation can you please have a look at this again and let me know if this can be merged or should be discarded? 

thank you

**Comment by phwizard** [comment]
@aasimtaif 
hey we appreciate your willingness to contribute but we can't merge with branch conflicts 

this screen now has a new design that will be implemented

if you'd like please feel free to submit some minor edit to some code file or readme file and I will merge it to reward for your willingness to contribute

thank you for your time

**Pull request closed without merging**
